language: cpp

sudo: required
dist: bionic

install: sudo apt-get install -y ninja-build

script:
  - cd panda-controller
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - ninja
  - ./panda-controller
