sudo: required
dist: bionic

before_install:
  - sudo ./install_dependecies_basic.sh

language: cpp

script:
  - cd panda-controller
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - ninja
  - ./panda-controller
