sudo: required
dist: bionic

before_install:
  - sudo apt-get install ninja-build
  - sudo apt-get install libeigen3-dev build-essential git libpoco-dev

language: cpp

script:
  - cd panda-controller
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - ninja
  - ./panda-controller
