language: cpp

sudo: required
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - ninja-build

script:
  - cd panda-controller
  - mkdir -p build
  - cd build
  - cmake -G Ninja ..
  - ninja
  - ./panda-controller
