dist: bionic

branches:
  only:
    - master

before_install:
  - sudo apt-get install doxygen

language: cpp

script:
  - cd documentation
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: documentation/build/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
