robot:
  ip: 192.168.3.101
  desk_username: franka
  desk_password: frankaRSI
nuc:
  hostname: biolab-017
  ssh_username: panda
  ssh_password: panda
  tcp_port: 5000
  udp_port: 4005
  camera_0:
    name: /dev/video10
    port: 6000
    on: true
  camera_1:
    name: /dev/video4
    port: 6001
    on: true
client:
  hostname: student-CELSIUS-W570
  udp_port: 4001

